version: '3.8'

services:
  # 1. DATABASE MYSQL (Konfigurasi lama kamu)
  db:
    image: mysql:8.0
    container_name: arahin_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arahin_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - arahin_network

  # 2. BACKEND NODE.JS
  backend:
    build: ./backend  # Mengambil Dockerfile dari folder backend
    container_name: arahin_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db  # PENTING: Mengubah localhost menjadi nama service 'db'
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=arahin_db
      - JWT_SECRET=bebop
      - PORT=3000
    depends_on:
      - db  # Tunggu database nyala dulu sebelum backend nyala
    networks:
      - arahin_network

  # 3. FRONTEND REACT/VITE
  frontend:
    build: ./FrontEnd # Mengambil Dockerfile dari folder FrontEnd
    container_name: arahin_frontend
    restart: always
    ports:
      - "8080:8080" # Sesuaikan dengan port yang digunakan Vite di Dockerfile
    depends_on:
      - backend # Tunggu backend nyala dulu
    networks:
      - arahin_network

# Mengatur penyimpanan data dan jaringan
volumes:
  db_data:

networks:
  arahin_network:
    driver: bridge