version: '3.8'

services:
  # 1. BACKEND NODE.JS
  backend:
    build: ./backend  # Mengambil Dockerfile dari folder backend
    container_name: arahin_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - arahin_network

  # 2. FRONTEND REACT/VITE
  frontend:
    build: ./FrontEnd # Mengambil Dockerfile dari folder FrontEnd
    container_name: arahin_frontend
    restart: always
    ports:
      - "8080:8080" # Sesuaikan dengan port yang digunakan Vite di Dockerfile
    env_file:
      - ./FrontEnd/.env 
    depends_on:
      - backend # Tunggu backend nyala dulu
    networks:
      - arahin_network

# Mengatur penyimpanan data dan jaringan
volumes:
  db_data:

networks:
  arahin_network:
    driver: bridge