name: Frontend ARAHIN Pipeline

on:
  push:
    branches: [ "main"]
    paths:
      - 'FrontEnd/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'FrontEnd/**'

  workflow_dispatch: 

jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FrontEnd
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Mengikuti versi di package.json kamu

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './FrontEnd/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build
